### ISSUE TITLE
Error in mlx.data.datasets.load_imagenet function due to missing 'archives' definition.

### ISSUE THREAD

**Issue by lizhelang** [ml-explore/mlx-data#68]
Traceback (most recent call last):
  File "/Users/lzl/FILE/Program/python/July17/federated-learning-master_mlx/mlx-imagenet-all.py", line 47, in <module>
    dataset_train = load_imagenet_data(train_dir,'train')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lzl/FILE/Program/python/July17/federated-learning-master_mlx/mlx-imagenet-all.py", line 32, in load_imagenet_data
    return load_imagenet(root=image_folder, split=plit, quiet=False, validate_download=True, tar_index_threads=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lzl/anaconda3/lib/python3.11/site-packages/mlx/data/datasets/imagenet.py", line 159, in load_imagenet
    metadata, val_gt = load_imagenet_devkit(root, quiet, validate_download)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lzl/anaconda3/lib/python3.11/site-packages/mlx/data/datasets/imagenet.py", line 74, in load_imagenet_devkit
    f"The devkit is missing from {str(root)}. Make sure to download {archives.name} from the imagenet website."
                                                                     ^^^^^^^^
NameError: name 'archives' is not defined. Did you mean: 'archive'?

**Comment by angeloskath** [comment]
Closing as this is already fixed on main.
